language: rust

rust:
  - nightly

os:
  - linux
  - osx

notifications:
  email:
    on_success: never
    on_failure: always

branches:
  only:
    # This is where pull requests from "bors r+" are built.
    - staging
    # This is where pull requests from "bors try" are built.
    - trying
    # Build pull requests.
    - master

cache:
  directories:
    - $HOME/.cargo
    - $HOME/Library/Caches/Homebrew

addons:
  apt:
    packages:
      - qemu-system-x86
  homebrew:
    packages:
      - qemu
    update: true

before_script:
  - rustup component add rust-src llvm-tools-preview
  - cargo install cargo-xbuild bootimage cargo-cache --debug -Z install-upgrade

script:
  - cargo xbuild
  - cargo bootimage
  - cargo xtest
  - cargo cache --autoclean
